extends Node

## Talent definitions for all characters.
## Indices match CharacterRegistry order:
## 0=snow_white, 1=scarlet, 2=rapunzel, 3=nayuta, 4=commander,
## 5=marian, 6=crown, 7=kilo, 8=cecil, 9=sin, 10=wells
##
## THREE TREES PER CHARACTER (tab-swapped in the talent overlay):
##   "attack" - upgrades the normal (left-click) attack
##   "skill"  - upgrades the right-click special ability
##   "burst"  - upgrades the burst ultimate
## Each tree uses the approved B1 8-slot "ability lanes" layout (col/row):
##   ROOT (col1,row0) -> A1 (col0,row0) / A2 (col2,row0)
##   MID  (col1,row1) -> B1 (col0,row1) / B2 (col2,row1)
##   CAP  (col2,row2) , SIG (col0,row2)
## requires: A1/A2/MID need ROOT; B1/B2/CAP need MID; SIG is standalone.
##
## Existing talents keep their real id/name/desc/tooltip/cost so gameplay
## (which looks them up by id) is unchanged. The roster is intentionally larger
## than the current talent set: empty slots are "Placeholder" entries to be
## filled in character-by-character later.

const PH_TIP := "Empty talent slot. To be designed."

static var TALENT_DATA := {
	0: [ # Snow White - Sniper with Turret
		# --- ATTACK ---
		{"id": "basic_attack", "name": "Seven Dwarves", "desc": "Long-range semi-auto sniper", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack", "start_unlocked": true,
		 "tooltip": "Semi-automatic sniper rifle with long range. Pierces all enemies."},
		{"id": "weak_point", "name": "Weak Point", "desc": "Hits mark enemies to take more damage", "col": 0, "row": 0, "requires": ["basic_attack"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Bullet hits permanently mark the target: it takes x2/x4/x6 damage from ALL sources until it dies."},
		{"id": "explosive_rounds", "name": "Explosive Rounds", "desc": "Bullet kills can explode", "col": 2, "row": 0, "requires": ["basic_attack"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Enemies killed by the bullet have a 10/25/50% chance to explode for damage equal to your attack."},
		{"id": "afterburn", "name": "Afterburn", "desc": "Bullets leave a trail of fire", "col": 1, "row": 1, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Your bullets leave a burning trail of fire along their path that injures enemies."},
		{"id": "burning", "name": "Burning", "desc": "Fire applies a burning DoT", "col": 0, "row": 1, "requires": ["afterburn"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Enemies injured by your fire burn for 2x/5x/10x your attack's damage over 5s. Refreshes while in the fire."},
		{"id": "inferno", "name": "Inferno", "desc": "Fire slows enemies", "col": 2, "row": 1, "requires": ["afterburn"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Your fire trails act as obstacles, slowing enemies inside them by 15/30/50%. Does not affect bosses."},
		{"id": "charging", "name": "Charging", "desc": "Hold to fire a wide shot", "col": 2, "row": 2, "requires": ["afterburn"], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Hold fire up to 3s to charge, then release: the shot (and its fire trail) becomes up to 5x wider."},
		{"id": "unyielding", "name": "Unyielding", "desc": "Bullet kills can heal you", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Enemies killed by your bullet (not fire or DoTs) have a 20% chance to heal you for 1 HP."},
		# --- SKILL ---
		{"id": "special", "name": "Auto-Turret", "desc": "Deploy auto-targeting turrets", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Deploys an auto-targeting turret with 4 missiles. Hold up to 2 turrets, 8s recharge."},
		{"id": "special_capacity", "name": "Ammo Cache", "desc": "+2 turret missile capacity", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "+2 missiles per turret. Max: 10 missiles."},
		{"id": "special_count", "name": "More Turrets", "desc": "+1 max turret", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "+1 turret per level. Max: 5 turrets."},
		{"id": "defensive_line", "name": "Defensive Line", "desc": "Turrets gain a damaging aura", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "Turrets project a large red aura dealing missile damage every second to enemies inside it."},
		{"id": "incendiary_ammo", "name": "Incendiary Ammo", "desc": "Missiles burn targets", "col": 0, "row": 1, "requires": ["defensive_line"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Enemies hit by turret missiles burn for 2x/4x/6x the missile's damage over 5s."},
		{"id": "armor_piercing", "name": "Armor-Piercing Ammo", "desc": "Missiles mark targets", "col": 2, "row": 1, "requires": ["defensive_line"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Enemies hit by missiles permanently take 2x/4x/6x more damage from all sources. Stacks with Weak Point."},
		{"id": "permanent_emplacement", "name": "Permanent Emplacement", "desc": "Turrets stay and reload", "col": 2, "row": 2, "requires": ["defensive_line"], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "Turrets never expire; they reload (~6s) instead of despawning. Deploying at your turret cap retires the oldest turret."},
		{"id": "detonation", "name": "Detonation", "desc": "Turrets explode when destroyed", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "When a turret is destroyed or retired, it detonates for 3x missile damage in 3x a missile's blast radius, applying missile debuffs."},
		# --- BURST ---
		{"id": "burst", "name": "Seven Dwarves", "desc": "Wide cone blast", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Fires a 90-degree cone dealing heavy damage scaled off your attack. Massive range."},
		{"id": "burst_burn", "name": "Incendiary Rounds", "desc": "Burst burns enemies hit", "col": 0, "row": 0, "requires": ["burst"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Enemies hit burn for 10/20/30% max HP/s for 3s. Bosses take 5/10/15%."},
		{"id": "burst_gauge", "name": "Fully Active", "desc": "Burst kills can refill gauge", "col": 2, "row": 0, "requires": ["burst"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Each enemy killed by the burst has a 33/66/100% chance to grant its normal burst gauge, enabling chaining."},
		{"id": "focused_fire", "name": "Focused Fire", "desc": "Hold burst to focus the beam", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Hold the burst key up to 2.5s to narrow the cone from 90 to 15 degrees; damage scales up to 6x as it narrows."},
		{"id": "pierce_through", "name": "Pierce Through", "desc": "Burst marks enemies", "col": 0, "row": 1, "requires": ["focused_fire"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Enemies hit by the burst take 2x/4x/6x more damage from all sources (Weak Point). Stacks with other marks."},
		{"id": "burst_stun", "name": "Stunned", "desc": "Burst stuns enemies", "col": 2, "row": 1, "requires": ["focused_fire"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Enemies hit by the burst are stunned for 2/5/7 seconds."},
		{"id": "century_prep", "name": "A CENTURY OF PREP TIME", "desc": "Burst deploys turrets everywhere", "col": 2, "row": 2, "requires": ["focused_fire"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Using the burst also deploys 10 turrets across the entire map."},
		{"id": "goddess_no_yield", "name": "A Goddess Who Cannot Yield", "desc": "Burst may not spend gauge", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "On burst: 25% chance to consume no gauge (stays full), 25% to consume half, 50% to consume it all."},
	],
	1: [ # Scarlet - Melee DPS
		# --- ATTACK ---
		{"id": "basic_attack", "name": "Fleetly Fading", "desc": "Sweeping sword slash", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack", "start_unlocked": true,
		 "tooltip": "Scarlet's default melee: a fast sword slash that sweeps the arc in front of her, hitting every enemy it touches."},
		{"id": "dodge", "name": "Dodge", "desc": "Invincible while dashing", "col": 0, "row": 0, "requires": ["basic_attack"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Dashing (Shift) makes Scarlet invincible. Lv2/Lv3 keep her invincible 0.5s/1s after the dash ends. A red scanline shows while invincible."},
		{"id": "eviscerate", "name": "Eviscerate", "desc": "Slashes cause heavy bleeding", "col": 2, "row": 0, "requires": ["basic_attack"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Slashed enemies bleed for 3x/5x/7x your attack's damage over 5s and leave a fading trail of blood."},
		{"id": "parry", "name": "Parry", "desc": "Slash deflects enemy bullets", "col": 1, "row": 1, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Enemy bullets caught in your sword's arc are knocked straight back the way they came instead of destroyed."},
		{"id": "evasion", "name": "Evasion", "desc": "Deflecting grants invincibility", "col": 0, "row": 1, "requires": ["parry"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "After deflecting a bullet, Scarlet is invincible for 0.5s/1s/1.5s (red scanline effect)."},
		{"id": "retaliation", "name": "Retaliation", "desc": "Deflected bullets hit harder", "col": 2, "row": 1, "requires": ["parry"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Deflected bullets deal 5x/10x/15x their original damage to the enemies they hit."},
		{"id": "roses_core", "name": "Rose's Core", "desc": "Slashes release rose petals", "col": 2, "row": 2, "requires": ["parry"], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Sword slashes also release 5 rose petal projectiles dealing half slash damage."},
		{"id": "i_am_cheating", "name": "I am cheating", "desc": "Repeat hits double in damage", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Each successive melee slash on the SAME enemy doubles its damage (x2, x4, x8, x16). Caps at x16. Tracked per enemy - built to melt bosses."},
		# --- SKILL ---
		{"id": "special", "name": "Dash Slash", "desc": "Dash leaves a damaging wave", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Dash releases a piercing wave dealing 8 damage. 5s cooldown."},
		{"id": "special_cd", "name": "Quick Slash", "desc": "-1s special cooldown", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "-1s cooldown per level. At max: 2s cooldown."},
		{"id": "special_heal", "name": "Vampiric Slash", "desc": "Heals 5/10/15% max HP per hit", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Wave heals per enemy hit while still dealing damage."},
		{"id": "nothing_personal", "name": "Nothing Personal, Kid", "desc": "Press skill again to teleport to the wave", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "While the Dash Slash wave is moving, press the skill again to vanish and reappear at the wave, striking for an AOE of 3x your skill damage. Does not heal (Vampiric Slash)."},
		{"id": "no_hard_feelings", "name": "No Hard Feelings", "desc": "Teleport AOE hits much harder", "col": 0, "row": 1, "requires": ["nothing_personal"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Multiplies the teleport AOE damage by x2/x4/x6 on top of the base 3x - up to 18x your skill damage."},
		{"id": "surprise", "name": "Surprise", "desc": "AOE survivors are stunned", "col": 2, "row": 1, "requires": ["nothing_personal"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Enemies hit by the teleport AOE that survive are stunned for 1/2/3 seconds."},
		{"id": "musashi", "name": "Musashi", "desc": "Hold to charge a bigger wave", "col": 2, "row": 2, "requires": ["nothing_personal"], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "Hold the skill button to charge: the Dash Slash wave grows up to 3x size and deals up to 3x damage."},
		{"id": "in_one_strike", "name": "In One Strike", "desc": "Wave kills explode", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "Enemies killed by the Dash Slash wave (not the teleport AOE) explode in a large blast dealing damage equal to your skill damage."},
		# --- BURST ---
		{"id": "burst", "name": "Scarlet Flash", "desc": "Blink-strike every enemy on screen", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Costs 50% HP. Teleports between every enemy on screen, striking each for massive damage, then ends at the last target."},
		{"id": "burst_execute", "name": "Execution", "desc": "Chance to instantly kill regulars", "col": 0, "row": 0, "requires": ["burst"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "The burst has a 33/66/100% chance to instantly kill each regular enemy. Elites and bosses take normal burst damage. Execution kills grant 1.5x XP."},
		{"id": "drink_to_victory", "name": "Drink to Victory", "desc": "Burst kills heal you", "col": 2, "row": 0, "requires": ["burst"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Heal 5/10/15% max HP for every enemy the burst kills."},
		{"id": "low_hp_damage", "name": "Scraping the Bottle", "desc": "Missing HP boosts damage", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Deal up to +500% damage based on missing HP (max at 15% HP). The burst locks in your HP at the moment it's triggered."},
		{"id": "expose_weakness", "name": "Expose Weakness", "desc": "Burst marks enemies permanently", "col": 0, "row": 1, "requires": ["low_hp_damage"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Enemies hit by the burst take 2x/4x/6x more damage from all sources - permanently, until they die."},
		{"id": "fire_in_my_veins", "name": "Fire In My Veins", "desc": "Burst kills can refill gauge", "col": 2, "row": 1, "requires": ["low_hp_damage"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Each enemy killed by the burst has a 33/66/100% chance to grant its normal burst gauge, enabling chaining."},
		{"id": "d1_crashout", "name": "D1 Crashout", "desc": "Time stays frozen after the burst", "col": 2, "row": 2, "requires": ["low_hp_damage"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "After the burst, enemies (and their bullets) stay frozen for 3 seconds while Scarlet can move and attack freely."},
		{"id": "goddess_no_yield", "name": "A GODDESS WHO CANNOT YIELD", "desc": "Burst may not spend gauge", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "On burst: 25% chance to consume no gauge (stays full), 25% to consume half, 50% to consume it all."},
	],
	2: [ # Rapunzel - Support Healer
		# --- ATTACK ---
		{"id": "basic_attack", "name": "Holy Grace", "desc": "Homing rocket launcher", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack", "start_unlocked": true,
		 "tooltip": "Fires a homing rocket that explodes on impact for heavy AoE damage."},
		{"id": "concussive_blast", "name": "Concussive Blast", "desc": "Rocket stuns enemies", "col": 0, "row": 0, "requires": ["basic_attack"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Enemies hit by the rocket or its explosion are stunned for 0.5/1/1.5 seconds."},
		{"id": "anti_armor", "name": "Anti-Armor Munitions", "desc": "Rocket marks enemies", "col": 2, "row": 0, "requires": ["basic_attack"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Enemies hit by the explosion permanently take x2/x4/x6 damage from ALL sources until they die."},
		{"id": "burning_desire", "name": "Burning Desire", "desc": "Rocket leaves a burning zone", "col": 1, "row": 1, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "The rocket's explosion leaves a burning zone on the ground that injures enemies standing in it."},
		{"id": "spread_love", "name": "Spread the Love", "desc": "Bigger burning zone", "col": 0, "row": 1, "requires": ["burning_desire"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Increases the size of the burning zone to 1.5x/2x/2.5x its default size."},
		{"id": "it_burns", "name": "It Burns", "desc": "Burning zone applies a DoT", "col": 2, "row": 1, "requires": ["burning_desire"], "max": 3, "cost": 1, "tree": "attack",
		 "tooltip": "Enemies that walk through the burning zone burn for 2x/4x/6x your attack's damage over 5s. Refreshes while in the zone."},
		{"id": "im_a_healer", "name": "I'm a Healer, But...", "desc": "Your kills heal you", "col": 2, "row": 2, "requires": ["burning_desire"], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Your kills heal you for 2% max HP."},
		{"id": "endless_desire", "name": "Endless Desire", "desc": "DoTs are permanent and stack endlessly", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Burn DoTs never expire and stack forever: each enemy gains a fresh stack on entering a burning zone and every second it stays inside, until it dies."},
		# --- SKILL ---
		{"id": "special", "name": "Divine Blessing", "desc": "Create a healing zone", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Heals 3% max HP/s for 9s. 10s cooldown."},
		{"id": "special_power", "name": "Rejuvenation", "desc": "Healing: 10/17.5/25% max HP/s", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Increases healing power dramatically."},
		{"id": "special_size", "name": "Expanding Aura", "desc": "Zone size +50/100/150%", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Larger healing radius: +50/100/150%."},
		{"id": "burning_sensation", "name": "A Burning Sensation", "desc": "Blessing burns enemies", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "Your Divine Blessing also burns enemies inside it each second for the same amount of HP it heals you (your max HP x heal %)."},
		{"id": "oooh_ahhhh", "name": "Oooh, Ahhhh", "desc": "Blessing stuns on first hit", "col": 0, "row": 1, "requires": ["burning_sensation"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "The first time an enemy is hit by a Divine Blessing's burn, it is stunned for 0.5/1/1.5s. Each blessing can stun a given enemy once; a newly deployed blessing can stun it again."},
		{"id": "more_more", "name": "More, more!", "desc": "Blessing burn damage x2/x4/x6", "col": 2, "row": 1, "requires": ["burning_sensation"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Increases the Divine Blessing's burn damage by 2x/4x/6x."},
		{"id": "personal_toy", "name": "Personal Toy", "desc": "A Blessing aura follows you", "col": 2, "row": 2, "requires": ["burning_sensation"], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "A Divine Blessing aura follows you at all times, but only while no deployable Divine Blessing is active."},
		{"id": "all_the_toys", "name": "All the Toys", "desc": "Keep the aura while one is deployed", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "Removes Personal Toy's restriction: your follow aura stays active even while a deployable Divine Blessing is out."},
		# --- BURST ---
		{"id": "burst", "name": "Garden of Shangri-La", "desc": "Massive heal + stun", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Full heal and stuns non-boss enemies for 4s."},
		{"id": "burst_stun", "name": "Blinding Radiance", "desc": "Burst stun +2/4/6s", "col": 0, "row": 0, "requires": ["burst"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Extends the burst's stun by 2/4/6 seconds. Does not affect bosses."},
		{"id": "lingering_light", "name": "Lingering Light", "desc": "Burst heals over time", "col": 2, "row": 0, "requires": ["burst"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "After bursting, heal 10% of your max HP per second for 6/8/10 seconds."},
		{"id": "burst_turrets", "name": "6,000? Really?", "desc": "Spawn 10 turrets across the map", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Summons 10 turrets spread across the entire map. Each has 4 ammo."},
		{"id": "incendiary_rockets", "name": "Incendiary Rockets", "desc": "Turret rockets leave burning ground", "col": 0, "row": 1, "requires": ["burst_turrets"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Rockets from 6,000? Really? leave a burning zone, burning enemies for 2x/4x/6x your attack's damage over 5s (like It Burns)."},
		{"id": "extra_stuffed", "name": "Extra Stuffed", "desc": "Turrets carry +2/4/6 ammo", "col": 2, "row": 1, "requires": ["burst_turrets"], "max": 3, "cost": 1, "tree": "burst",
		 "tooltip": "Each 6,000? Really? turret carries +2/4/6 extra rockets. The camera stays zoomed out until the whole barrage finishes firing."},
		{"id": "anti_queen", "name": "Anti-Queen Bombardment", "desc": "Hold burst to aim the barrage", "col": 2, "row": 2, "requires": ["burst_turrets"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Hold the burst key ~1s to paint a target with a laser designator: every rocket from 6,000? Really? rains down on your cursor instead of the nearest enemies. A quick tap still bursts normally."},
		{"id": "goddess_no_yield", "name": "A Goddess Who Cannot Yield", "desc": "Burst may not spend gauge", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "On burst: 25% chance to consume no gauge (stays full), 25% to consume half, 50% to consume it all."},
	],
	3: [ # Nayuta - SMG with Clone Summoning & Galaxy Burst
		# --- ATTACK ---
		{"id": "basic_attack", "name": "Duplicity", "desc": "Kills can spawn clones", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "10% chance to spawn a Nayuta clone when you kill an enemy."},
		{"id": "atk_a1", "name": "Placeholder", "desc": "", "col": 0, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_a2", "name": "Placeholder", "desc": "", "col": 2, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		# --- SKILL ---
		{"id": "special", "name": "Summon Clone", "desc": "Summon a fighting clone", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Summons clone with 1/2 HP/attack. Lives until killed. 8s cooldown."},
		{"id": "special_heal", "name": "NIMPH Return", "desc": "Clone death heals 20/35/50%", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "When clone dies, gold sparkles travel to you and heal % max HP."},
		{"id": "special_weapon", "name": "WEAPON MASTER", "desc": "Clones can use +sword/rocket/sniper", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Adds new weapons to clone pool. Random selection on summon."},
		{"id": "return_unto_me", "name": "RETURN UNTO ME", "desc": "Hold special: consume clones for damage", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "Hold the special button ~1s to destroy all your clones, gaining +50% damage per clone destroyed for 5s. With NIMPH Return, the destroyed clones also heal you."},
		{"id": "skl_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["return_unto_me"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["return_unto_me"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["return_unto_me"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		# --- BURST ---
		{"id": "burst", "name": "Asceticism", "desc": "Massive space explosion", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Purple galaxy explosion damages all enemies on screen."},
		{"id": "burst_stun", "name": "Nirvana", "desc": "Stun bosses/elites 8s", "col": 0, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Bosses and elites hit by burst are stunned for 8 seconds."},
		{"id": "burst_debuff", "name": "Impermanence", "desc": "Bosses/elites take 50% more damage", "col": 2, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Marked enemies take +50% damage. Purple star effect shows debuff."},
		{"id": "brt_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
	],
	4: [ # Commander - Assault Rifle with Time Freeze & Ally Summons
		# --- ATTACK ---
		{"id": "basic_attack", "name": "Obviously Anderson", "desc": "2x Burst gauge generation", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Attacks generate Burst gauge at 2x rate."},
		{"id": "atk_a1", "name": "Placeholder", "desc": "", "col": 0, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_a2", "name": "Placeholder", "desc": "", "col": 2, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		# --- SKILL ---
		{"id": "special", "name": "I've Got a Meeting", "desc": "Stun all enemies in time", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Stuns all enemies on screen for 3s. 12s cooldown."},
		{"id": "special_duration", "name": "Hold That Thought", "desc": "+1s stun duration", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "+1s duration per level. Max: 6s stun."},
		{"id": "special_cooldown", "name": "Enikk is Calling", "desc": "-2s special cooldown", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "-2s cooldown per level. Min: 6s cooldown."},
		{"id": "skl_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		# --- BURST ---
		{"id": "burst", "name": "Goddess Squad", "desc": "Summon AI allies", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Summons 1 random ally (Scarlet/Snow White/Rapunzel) for 10s."},
		{"id": "burst_left", "name": "Reinforcements I", "desc": "Summon +1 ally", "col": 0, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Summons 2 allies instead of 1."},
		{"id": "burst_right", "name": "Reinforcements II", "desc": "Summon +1 ally", "col": 2, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Summons 3 allies instead of 2. All 3 types available."},
		{"id": "wave_heal", "name": "Good Genes", "desc": "Heals at wave end", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Heals at wave end (or every 30s in timerless modes). Heals 2-10 based on Burst gauge: lower gauge = more healing."},
		{"id": "brt_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["wave_heal"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["wave_heal"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["wave_heal"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
	],
	5: [ # Marian - Minigun with Charm & Epic Beam
		# --- ATTACK ---
		{"id": "beam_absorb", "name": "She'll Eat Anything", "desc": "Absorb boss beams", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Boss beams deal no damage to Marian. Instead, grants 5s of +100% damage and enhanced beam."},
		{"id": "basic_attack", "name": "Main Heroine", "desc": "Minigun becomes a beam cannon", "col": 0, "row": 0, "requires": ["beam_absorb"], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Replace minigun with a continuous purple beam cannon."},
		{"id": "atk_a2", "name": "Placeholder", "desc": "", "col": 2, "row": 0, "requires": ["beam_absorb"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["beam_absorb"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		# --- SKILL ---
		{"id": "special", "name": "Rapture Queen", "desc": "AoE charm converts enemies", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Charms normal enemies in area to fight for you. 10s cooldown."},
		{"id": "special_size", "name": "Queen Gene", "desc": "AoE + enemy types", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "AoE +50/100/200%. Lv1: Also affects Tanks. Lv2: Also affects Elites. Lv3: Stuns Bosses for 3s."},
		{"id": "special_cooldown", "name": "Royal Dominion", "desc": "-2s special cooldown", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "-2s cooldown per level. At max: 4s cooldown."},
		{"id": "skl_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		# --- BURST ---
		{"id": "burst", "name": "New World", "desc": "5s aimable laser beam", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "5 second aimable purple laser beam. Follow mouse to aim."},
		{"id": "burst_left", "name": "Missile Barrage", "desc": "Fire 4 homing missiles every 2.5s", "col": 0, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "During burst, fires 4 homing missiles at random enemies twice."},
		{"id": "burst_right", "name": "Queen Beam", "desc": "Beam leaves purple fire", "col": 2, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Beam leaves a 5s burning trail that damages enemies."},
		{"id": "brt_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
	],
	6: [ # Crown - Minigun with Cavalry Charge & Golden Nova
		# --- ATTACK ---
		{"id": "basic_attack", "name": "Royal Knowledge", "desc": "Earn XP at 2x rate", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Earn XP at 2x rate."},
		{"id": "atk_a1", "name": "Placeholder", "desc": "", "col": 0, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_a2", "name": "Placeholder", "desc": "", "col": 2, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		# --- SKILL ---
		{"id": "special", "name": "Summon Trombe", "desc": "Summon Trombe, charge forward", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Summon Trombe, charge forward with V-damage. Invincible. 2.5s duration, 10s cooldown."},
		{"id": "special_cooldown", "name": "Swift Steed", "desc": "-1.5s charge cooldown", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "-1.5s cooldown per level. Min: 5.5s cooldown."},
		{"id": "special_explosion", "name": "Royal Charge", "desc": "Survivors explode for 1x/2x/3x ATK", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Enemies hit but not killed glow gold, explode for 1x/2x/3x ATK."},
		{"id": "trombe_stacking", "name": "How Does This Keep Working?", "desc": "Trombe grows with each use", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill",
		 "tooltip": "Trombe +35% size per use. Max 3 stacks, 12s each."},
		{"id": "skl_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["trombe_stacking"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["trombe_stacking"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["trombe_stacking"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		# --- BURST ---
		{"id": "burst", "name": "Last Kingdom", "desc": "Screen-wide blast", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Massive golden AoE blast fills the screen for massive damage."},
		{"id": "burst_charge", "name": "One for All", "desc": "Burst generates burst gauge", "col": 0, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Burst damage now contributes to burst gauge charging."},
		{"id": "burst_beam", "name": "Naked King", "desc": "Adds 3s forward beam", "col": 2, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Adds massive golden frontal beam lasting 3s dealing huge damage."},
		{"id": "brt_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
	],
	7: [ # Kilo - Shotgun DPS
		# --- ATTACK ---
		{"id": "talos_ammo", "name": "Build-a-Bullet", "desc": "Shots regenerate ammo", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Every 3rd bullet fired regenerates 1 ammo."},
		{"id": "atk_a1", "name": "Placeholder", "desc": "", "col": 0, "row": 0, "requires": ["talos_ammo"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_a2", "name": "Placeholder", "desc": "", "col": 2, "row": 0, "requires": ["talos_ammo"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["talos_ammo"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		# --- SKILL ---
		{"id": "special", "name": "Explosive Shells", "desc": "Pellets create explosive beams", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Pellet hits trigger V-shaped explosions behind enemies. 3s cooldown."},
		{"id": "special_burn", "name": "Searing Beams", "desc": "Beams burn for 15/25/35% HP/s", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "3s burn. Elites/bosses take 5/10/15% instead."},
		{"id": "special_size", "name": "Amplified Blast", "desc": "Explosion +50/100/200% size & +30/60/100% dmg", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Bigger and more damaging explosions."},
		{"id": "skl_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		# --- BURST ---
		{"id": "burst", "name": "Assign Priority", "desc": "Rapid fire frenzy", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Infinite ammo, rapid fire, 2.2x damage for 5s."},
		{"id": "burst_duration", "name": "Extended Assault", "desc": "Burst lasts 10 seconds", "col": 0, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Doubles burst duration from 5s to 10s."},
		{"id": "burst_invuln", "name": "T.A.L.O.S. Shield", "desc": "Invincible during burst", "col": 2, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Grants invincibility for burst duration."},
		{"id": "emergency_repairs", "name": "Emergency Repairs", "desc": "Heal while standing still", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Stand still for 2.5s to begin repairs, restoring 10% max HP per second. You can still fire."},
		{"id": "brt_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["emergency_repairs"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["emergency_repairs"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["emergency_repairs"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
	],
	8: [ # Cecil - SMG with Drones & Hacking Burst
		# --- ATTACK ---
		{"id": "basic_attack", "name": "Three Wishes...", "desc": "Gain 3 extra lives", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Gain 3 extra lives. Revive at full HP with 5s invincibility."},
		{"id": "atk_a1", "name": "Placeholder", "desc": "", "col": 0, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_a2", "name": "Placeholder", "desc": "", "col": 2, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		# --- SKILL ---
		{"id": "special", "name": "Drone Deploy", "desc": "Deploy 2 companion drones", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Deploys 2 invincible drones. Right-click toggles Hunt/Shield modes."},
		{"id": "special_speed", "name": "Overclock", "desc": "Drone speed +50/100/200%", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Drones move and attack faster per level."},
		{"id": "special_shield", "name": "Barrier Protocol", "desc": "Shield absorbs +1 hit", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Shield mode absorbs +1 hit per level. Max: 4 hits."},
		{"id": "skl_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		# --- BURST ---
		{"id": "burst", "name": "System Hack", "desc": "Freeze & convert enemies", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Freeze all enemies 1.5s. Non-elite/boss become permanent allies."},
		{"id": "burst_damage", "name": "Malware", "desc": "Hacked allies +50% damage", "col": 0, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Converted enemies deal 50% more damage."},
		{"id": "burst_boss", "name": "Exploit", "desc": "25% max HP to elites/bosses", "col": 2, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Elites and bosses take 25% of their max HP as damage after stun."},
		{"id": "eden_shield", "name": "Noah's Defiance", "desc": "Kills generate a shield", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Kills by player (not summons) generate shield. Max 50% of HP."},
		{"id": "brt_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["eden_shield"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["eden_shield"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["eden_shield"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
	],
	9: [ # Sin - SMG with Charm & Life Drain
		# --- ATTACK ---
		{"id": "basic_attack", "name": "Magnetic Personality", "desc": "Aura mind-controls enemies", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Passive aura permanently mind-controls nearby regular enemies."},
		{"id": "atk_a1", "name": "Placeholder", "desc": "", "col": 0, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_a2", "name": "Placeholder", "desc": "", "col": 2, "row": 0, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["basic_attack"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		# --- SKILL ---
		{"id": "special", "name": "Heavy Talker", "desc": "AoE charm converts enemies", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Charms normal enemies in area to fight for you. 10s cooldown."},
		{"id": "special_size", "name": "Loud Talker", "desc": "Charm AoE +50/100/200%", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Increases charm area of effect."},
		{"id": "special_cooldown", "name": "Captivating", "desc": "Charmed deaths empower Sin", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Lv1: Charmed enemy deaths explode. Lv2: Also heal 1 HP. Lv3: Can charm Tanks."},
		{"id": "skl_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		# --- BURST ---
		{"id": "burst", "name": "Words Can Kill", "desc": "ATK DOT that heals", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "4s DOT dealing 10x ATK damage every second. Heals 5% max HP per enemy hit per tick."},
		{"id": "burst_charge", "name": "You'll Steal for Me", "desc": "Kills during burst charge gauge", "col": 0, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Enemy kills during burst contribute to burst gauge."},
		{"id": "burst_explode", "name": "You'll Die for Me", "desc": "Enemies explode on death", "col": 2, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Enemies dying during burst explode for 4 damage. Scales with ATK."},
		{"id": "wish_save", "name": "I WISH They Were Gone", "desc": "Survive death once per match", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "Once per match: When you would die, freeze time and destroy all non-boss enemies. Grants 3s invulnerability."},
		{"id": "brt_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["wish_save"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["wish_save"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["wish_save"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
	],
	10: [ # Wells - Time Traveler Sniper
		# --- ATTACK ---
		{"id": "ally_speed", "name": "I Can't Predict the Future", "desc": "Summons move 50% faster", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "All summoned allies move 50% faster."},
		{"id": "chrono_intangibility", "name": "Chrono-Intangibility", "desc": "Bullets pierce shields/boulders", "col": 0, "row": 0, "requires": ["ally_speed"], "max": 1, "cost": 1, "tree": "attack",
		 "tooltip": "Player bullets phase through shields and boulders."},
		{"id": "atk_a2", "name": "Placeholder", "desc": "", "col": 2, "row": 0, "requires": ["ally_speed"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["ally_speed"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["atk_mid"], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		{"id": "atk_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "attack", "tooltip": PH_TIP},
		# --- SKILL ---
		{"id": "special", "name": "Mnemosyne Project", "desc": "Hold E for Bullet Time", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true, "tree": "skill",
		 "tooltip": "Hold E to slow time (Bullet Time). Costs Fuel. fuel recharges over time."},
		{"id": "special_upgrade1", "name": "Secrets of the Past", "desc": "Lv1: Heal. Lv2: Speed. Lv3: Inf Ammo.", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Lvl 1: Heal 25% HP/s. Lvl 2: +100% Speed. Lvl 3: Infinite Ammo."},
		{"id": "special_upgrade2", "name": "Dust to Dust", "desc": "DOT to all enemies", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1, "tree": "skill",
		 "tooltip": "Normal: 10/25/34%. Elites: 5/10/15%. Bosses: 1/2/3% HP/s."},
		{"id": "skl_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["skl_mid"], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		{"id": "skl_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "skill", "tooltip": PH_TIP},
		# --- BURST ---
		{"id": "burst", "name": "Echoes of Hope", "desc": "Summon Marian", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "burst": true, "tree": "burst",
		 "tooltip": "Summons Marian as an ally for 10s."},
		{"id": "burst_upgrade1", "name": "A Great King", "desc": "Also summons Crown", "col": 0, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "\"Illiterate, but great.\""},
		{"id": "burst_upgrade2", "name": "A Fellow Nerd", "desc": "Also summons Kilo", "col": 2, "row": 0, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst",
		 "tooltip": "\"Smells bad, tastes worse.\""},
		{"id": "brt_mid", "name": "Placeholder", "desc": "", "col": 1, "row": 1, "requires": ["burst"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b1", "name": "Placeholder", "desc": "", "col": 0, "row": 1, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_b2", "name": "Placeholder", "desc": "", "col": 2, "row": 1, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_cap", "name": "Placeholder", "desc": "", "col": 2, "row": 2, "requires": ["brt_mid"], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
		{"id": "brt_sig", "name": "Placeholder", "desc": "", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 1, "tree": "burst", "tooltip": PH_TIP},
	],
}
