extends Node

## Talent definitions for all characters.
## Indices match CharacterRegistry order:
## 0=snow_white, 1=scarlet, 2=rapunzel, 3=nayuta, 4=commander,
## 5=marian, 6=crown, 7=kilo, 8=cecil, 9=sin, 10=wells
##
## Row 0: special + mods. Row 1: burst + mods.
## Row 2: signature talents migrated from the old character shop (Phase 3).
##   - Signature (col 0): no prerequisite, 2 SP (3 SP for the strongest).
##   - Capstone (col 2): requires burst (or special where it modifies it), 3 SP.

static var TALENT_DATA := {
	0: [ # Snow White - Sniper with Turret
		{"id": "special", "name": "Auto-Turret", "desc": "Deploy auto-targeting turrets", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Deploys turret with 4 missiles. 1 charge, 8s recharge."},
		{"id": "special_capacity", "name": "Ammo Cache", "desc": "+2 turret missile capacity", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "+2 missiles per turret. Max: 10 missiles."},
		{"id": "special_count", "name": "More Turrets", "desc": "+2 max turret charges", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "+2 charges per level. Max: 7 turrets."},
		{"id": "burst", "name": "Seven Dwarves", "desc": "", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "90° blast dealing 50 damage. Massive range."},
		{"id": "burst_burn", "name": "Incendiary Rounds", "desc": "Burns enemies for 34% max HP/s", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "3s burn. Bosses take 12% max HP/s instead."},
		{"id": "burst_gauge", "name": "Fully Active", "desc": "Kills during burst refill gauge", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Burst kills generate burst gauge for chaining."},
		{"id": "basic_attack", "name": "Best Girl", "desc": "Attacks leave burning trails", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "Attacks leave burning trails for 1.5s. Enemies take 3% HP/s burn damage for 10s. Bosses take 1% HP/s."},
		{"id": "master_mechanic", "name": "Master Mechanic", "desc": "Greatly increased ammo capacity", "col": 2, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "Ammo capacity: +100%."},
	],
	1: [ # Scarlet - Melee DPS
		{"id": "special", "name": "Dash Slash", "desc": "Dash leaves a damaging wave", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Dash releases a piercing wave dealing 8 damage. 4s cooldown."},
		{"id": "special_cd", "name": "Quick Dash", "desc": "-1s special cooldown", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "-1s cooldown per level. At max: 1s cooldown."},
		{"id": "special_heal", "name": "Vampiric Slash", "desc": "Heals 5/15/25% max HP per hit", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Wave heals per enemy hit while still dealing damage."},
		{"id": "burst", "name": "Scarlet Flash", "desc": "Devastating slash wave", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "Costs 50% HP. Hits all enemies on screen. Teleports to last target."},
		{"id": "burst_execute", "name": "Execution", "desc": "Instant kill + heals 15% max HP per kill", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Regular enemies die instantly. Heals 15% max HP per kill. Elites/bosses take normal damage."},
		{"id": "burst_vuln", "name": "Expose Weakness", "desc": "Surviving targets take 50% more damage", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Marked enemies take +50% damage from all sources."},
		{"id": "basic_attack", "name": "Rose's Core", "desc": "Slashes release rose petals", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "Sword slashes release 5 rose petal projectiles dealing full damage."},
		{"id": "low_hp_damage", "name": "Scraping the Bottle", "desc": "Missing HP boosts damage", "col": 2, "row": 2, "requires": ["burst"], "max": 1, "cost": 3,
		 "tooltip": "Deal up to +100% damage based on missing HP (max bonus at 15% HP)."},
	],
	2: [ # Rapunzel - Support Healer
		{"id": "special", "name": "Divine Blessing", "desc": "Create a healing zone", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Heals 3% max HP/s for 9s. 10s cooldown."},
		{"id": "special_power", "name": "Rejuvenation", "desc": "Healing: 10/17.5/25% max HP/s", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Increases healing power dramatically."},
		{"id": "special_size", "name": "Expanding Aura", "desc": "Zone size +50/150/300%", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Larger healing radius."},
		{"id": "burst", "name": "Garden of Shangri-La", "desc": "Massive heal + stun", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "Full heal + 4s stun on all enemies."},
		{"id": "burst_stun", "name": "Blinding Radiance", "desc": "Stun duration increased to 8s", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Doubles stun from 4s to 8s."},
		{"id": "burst_turrets", "name": "6,000? Really?", "desc": "Spawn 20 turrets across the map", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Summons 20 Snow White turrets spread across the entire map. Each has 4 ammo."},
		{"id": "basic_attack", "name": "I'm a Healer, But...", "desc": "Your kills heal you", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "Your kills heal you for 2% max HP."},
		{"id": "burning_sensation", "name": "A Burning Sensation", "desc": "Healing Aura burns enemies", "col": 2, "row": 2, "requires": ["special"], "max": 1, "cost": 3,
		 "tooltip": "Healing Aura also burns enemies for equivalent damage (3-25% HP/s). Bosses capped at 3%."},
	],
	3: [ # Nayuta - SMG with Clone Summoning & Galaxy Burst
		{"id": "special", "name": "Summon Clone", "desc": "Summon a fighting clone", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Summons clone with 1/2 HP/attack. Lives until killed. 8s cooldown."},
		{"id": "special_heal", "name": "NIMPH Return", "desc": "Clone death heals 20/35/50%", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "When clone dies, gold sparkles travel to you and heal % max HP."},
		{"id": "special_weapon", "name": "WEAPON MASTER", "desc": "Clones can use +sword/rocket/sniper", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Adds new weapons to clone pool. Random selection on summon."},
		{"id": "burst", "name": "Asceticism", "desc": "Massive space explosion", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "Purple galaxy explosion damages all enemies on screen."},
		{"id": "burst_stun", "name": "Nirvana", "desc": "Stun bosses/elites 8s", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Bosses and elites hit by burst are stunned for 8 seconds."},
		{"id": "burst_debuff", "name": "Impermanence", "desc": "Bosses/elites take 50% more damage", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Marked enemies take +50% damage. Purple star effect shows debuff."},
		{"id": "basic_attack", "name": "Duplicity", "desc": "Kills can spawn clones", "col": 1, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "10% chance to spawn a Nayuta clone when you kill an enemy."},
	],
	4: [ # Commander - Assault Rifle with Time Freeze & Ally Summons
		{"id": "special", "name": "I've Got a Meeting", "desc": "Stun all enemies in time", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Stuns all enemies on screen for 3s. 12s cooldown."},
		{"id": "special_duration", "name": "Hold That Thought", "desc": "+1s stun duration", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "+1s duration per level. Max: 6s stun."},
		{"id": "special_cooldown", "name": "Enikk is Calling", "desc": "-2s special cooldown", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "-2s cooldown per level. Min: 6s cooldown."},
		{"id": "burst", "name": "Goddess Squad", "desc": "Summon AI allies", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "Summons 1 random ally (Scarlet/Snow White/Rapunzel) for 10s."},
		{"id": "burst_left", "name": "Reinforcements I", "desc": "Summon +1 ally", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Summons 2 allies instead of 1."},
		{"id": "burst_right", "name": "Reinforcements II", "desc": "Summon +1 ally", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Summons 3 allies instead of 2. All 3 types available."},
		{"id": "basic_attack", "name": "Obviously Anderson", "desc": "2x Burst gauge generation", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "Attacks generate Burst gauge at 2x rate."},
		{"id": "wave_heal", "name": "Good Genes", "desc": "Heals at wave end", "col": 2, "row": 2, "requires": ["burst"], "max": 1, "cost": 3,
		 "tooltip": "Heals at wave end (or every 30s in timerless modes). Heals 2-10 based on Burst gauge: lower gauge = more healing."},
	],
	5: [ # Marian - Minigun with Charm & Epic Beam
		{"id": "special", "name": "Rapture Queen", "desc": "AoE charm converts enemies", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Charms normal enemies in area to fight for you. 10s cooldown."},
		{"id": "special_size", "name": "Queen Gene", "desc": "AoE + enemy types", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "AoE +50/100/200%. Lv1: Also affects Tanks. Lv2: Also affects Elites. Lv3: Stuns Bosses for 3s."},
		{"id": "special_cooldown", "name": "Royal Dominion", "desc": "-2s special cooldown", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "-2s cooldown per level. At max: 4s cooldown."},
		{"id": "burst", "name": "New World", "desc": "5s aimable laser beam", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "5 second aimable purple laser beam. Follow mouse to aim."},
		{"id": "burst_left", "name": "Missile Barrage", "desc": "Fire 4 homing missiles every 2.5s", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "During burst, fires 4 homing missiles at random enemies twice."},
		{"id": "burst_right", "name": "Queen Beam", "desc": "Beam leaves purple fire", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Beam leaves a 5s burning trail that damages enemies."},
		{"id": "basic_attack", "name": "Main Heroine", "desc": "Minigun becomes a beam cannon", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "Replace minigun with a continuous purple beam cannon."},
		{"id": "beam_absorb", "name": "She'll Eat Anything", "desc": "Absorb boss beams", "col": 2, "row": 2, "requires": ["burst"], "max": 1, "cost": 3,
		 "tooltip": "Boss beams deal no damage to Marian. Instead, grants 5s of +100% damage and enhanced beam."},
	],
	6: [ # Crown - Minigun with Cavalry Charge & Golden Nova
		{"id": "special", "name": "Summon Trombe", "desc": "Summon Trombe, charge forward", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Summon Trombe, charge forward with V-damage. Invincible. 2.5s duration, 10s cooldown."},
		{"id": "special_cooldown", "name": "Swift Steed", "desc": "-1.5s charge cooldown", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "-1.5s cooldown per level. Min: 5.5s cooldown."},
		{"id": "special_explosion", "name": "Royal Charge", "desc": "Survivors explode for 1x/2x/3x ATK", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Enemies hit but not killed glow gold, explode for 1x/2x/3x ATK."},
		{"id": "burst", "name": "Last Kingdom", "desc": "Screen-wide blast", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "Massive golden AoE blast fills the screen for massive damage."},
		{"id": "burst_charge", "name": "One for All", "desc": "Burst generates burst gauge", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Burst damage now contributes to burst gauge charging."},
		{"id": "burst_beam", "name": "Naked King", "desc": "Adds 3s forward beam", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Adds massive golden frontal beam lasting 3s dealing huge damage."},
		{"id": "basic_attack", "name": "Royal Knowledge", "desc": "Earn XP at 2x rate", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 3,
		 "tooltip": "Earn XP at 2x rate."},
		{"id": "trombe_stacking", "name": "How Does This Keep Working?", "desc": "Trombe grows with each use", "col": 2, "row": 2, "requires": ["special"], "max": 1, "cost": 3,
		 "tooltip": "Trombe +35% size per use. Max 3 stacks, 12s each."},
	],
	7: [ # Kilo - Shotgun DPS
		{"id": "special", "name": "Explosive Shells", "desc": "Pellets create explosive beams", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Pellet hits trigger V-shaped explosions behind enemies. 3s cooldown."},
		{"id": "special_burn", "name": "Searing Beams", "desc": "Beams burn for 15/25/35% HP/s", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "3s burn. Elites/bosses take 5/10/15% instead."},
		{"id": "special_size", "name": "Amplified Blast", "desc": "Explosion +50/100/200% size & +30/60/100% dmg", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Bigger and more damaging explosions."},
		{"id": "burst", "name": "Assign Priority", "desc": "Rapid fire frenzy", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "Infinite ammo, rapid fire, 2.2x damage for 5s."},
		{"id": "burst_duration", "name": "Extended Assault", "desc": "Burst lasts 10 seconds", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Doubles burst duration from 5s to 10s."},
		{"id": "burst_invuln", "name": "T.A.L.O.S. Shield", "desc": "Invincible during burst", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Grants invincibility for burst duration."},
		{"id": "talos_ammo", "name": "Build-a-Bullet", "desc": "Shots regenerate ammo", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "Every 3rd bullet fired regenerates 1 ammo."},
		{"id": "core_drop", "name": "Filling Crown's Ball Pit", "desc": "+50% core drop chance", "col": 2, "row": 2, "requires": ["burst"], "max": 1, "cost": 3,
		 "tooltip": "+50% core drop chance. Bosses have 50% chance for extra core."},
	],
	8: [ # Cecil - SMG with Drones & Hacking Burst
		{"id": "special", "name": "Drone Deploy", "desc": "Deploy 2 companion drones", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Deploys 2 invincible drones. Right-click toggles Hunt/Shield modes."},
		{"id": "special_speed", "name": "Overclock", "desc": "Drone speed +50/100/200%", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Drones move and attack faster per level."},
		{"id": "special_shield", "name": "Barrier Protocol", "desc": "Shield absorbs +1 hit", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Shield mode absorbs +1 hit per level. Max: 4 hits."},
		{"id": "burst", "name": "System Hack", "desc": "Freeze & convert enemies", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "Freeze all enemies 1.5s. Non-elite/boss become permanent allies."},
		{"id": "burst_damage", "name": "Malware", "desc": "Hacked allies +50% damage", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Converted enemies deal 50% more damage."},
		{"id": "burst_boss", "name": "Exploit", "desc": "25% max HP to elites/bosses", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Elites and bosses take 25% of their max HP as damage after stun."},
		{"id": "basic_attack", "name": "Three Wishes...", "desc": "Gain 3 extra lives", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 3,
		 "tooltip": "Gain 3 extra lives. Revive at full HP with 5s invincibility."},
		{"id": "eden_shield", "name": "Noah's Defiance", "desc": "Kills generate a shield", "col": 2, "row": 2, "requires": ["burst"], "max": 1, "cost": 3,
		 "tooltip": "Kills by player (not summons) generate shield. Max 50% of HP."},
	],
	9: [ # Sin - SMG with Charm & Life Drain
		{"id": "special", "name": "Heavy Talker", "desc": "AoE charm converts enemies", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Charms normal enemies in area to fight for you. 10s cooldown."},
		{"id": "special_size", "name": "Loud Talker", "desc": "Charm AoE +50/100/200%", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Increases charm area of effect."},
		{"id": "special_cooldown", "name": "Captivating", "desc": "Charmed deaths empower Sin", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Lv1: Charmed enemy deaths explode. Lv2: Also heal 1 HP. Lv3: Can charm Tanks."},
		{"id": "burst", "name": "Words Can Kill", "desc": "ATK DOT that heals", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "4s DOT dealing 10x ATK damage every second. Heals 5% max HP per enemy hit per tick."},
		{"id": "burst_charge", "name": "You'll Steal for Me", "desc": "Kills during burst charge gauge", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Enemy kills during burst contribute to burst gauge."},
		{"id": "burst_explode", "name": "You'll Die for Me", "desc": "Enemies explode on death", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "Enemies dying during burst explode for 4 damage. Scales with ATK."},
		{"id": "basic_attack", "name": "Magnetic Personality", "desc": "Aura mind-controls enemies", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "Passive aura permanently mind-controls nearby regular enemies."},
		{"id": "wish_save", "name": "I WISH They Were Gone", "desc": "Survive death once per match", "col": 2, "row": 2, "requires": ["burst"], "max": 1, "cost": 3,
		 "tooltip": "Once per match: When you would die, freeze time and destroy all non-boss enemies. Grants 3s invulnerability."},
	],
	10: [ # Wells - Time Traveler Sniper
		{"id": "special", "name": "Mnemosyne Project", "desc": "Hold E for Bullet Time", "col": 1, "row": 0, "requires": [], "max": 1, "cost": 1, "special": true,
		 "tooltip": "Hold E to slow time (Bullet Time). Costs Fuel. fuel recharges over time."},
		{"id": "special_upgrade1", "name": "Secrets of the Past", "desc": "Lv1: Heal. Lv2: Speed. Lv3: Inf Ammo.", "col": 0, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Lvl 1: Heal 25% HP/s. Lvl 2: +100% Speed. Lvl 3: Infinite Ammo."},
		{"id": "special_upgrade2", "name": "Dust to Dust", "desc": "DOT to all enemies", "col": 2, "row": 0, "requires": ["special"], "max": 3, "cost": 1,
		 "tooltip": "Normal: 10/25/34%. Elites: 5/10/15%. Bosses: 1/2/3% HP/s."},
		{"id": "burst", "name": "Echoes of Hope", "desc": "Summon Marian", "col": 1, "row": 1, "requires": ["special"], "max": 1, "cost": 1, "burst": true,
		 "tooltip": "Summons Marian as an ally for 10s."},
		{"id": "burst_upgrade1", "name": "A Great King", "desc": "Also summons Crown", "col": 0, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "\"Illiterate, but great.\""},
		{"id": "burst_upgrade2", "name": "A Fellow Nerd", "desc": "Also summons Kilo", "col": 2, "row": 1, "requires": ["burst"], "max": 1, "cost": 1,
		 "tooltip": "\"Smells bad, tastes worse.\""},
		{"id": "ally_speed", "name": "I Can't Predict the Future", "desc": "Summons move 50% faster", "col": 0, "row": 2, "requires": [], "max": 1, "cost": 2,
		 "tooltip": "All summoned allies move 50% faster."},
		{"id": "chrono_intangibility", "name": "Chrono-Intangibility", "desc": "Bullets pierce shields/boulders", "col": 2, "row": 2, "requires": ["burst"], "max": 1, "cost": 3,
		 "tooltip": "Player bullets phase through shields and boulders."},
	],
}
