extends Node2D
class_name CecilShield
## Cecil's protective shield generated by drones in shield mode
## Absorbs hits, refreshes over time, blue semi-transparent bubble

var owner_player: Node2D = null

# Shield stats
var max_hits: int = 1
var current_hits: int = 1
var recharge_time: float = 2.0
var _recharge_timer: float = 0.0
var _is_recharging: bool = false

# Visual
var shield_radius: float = 75.0  # Larger radius to not overlap player
var _pulse_time: float = 0.0
var _hit_flash: float = 0.0
var _is_active: bool = false

# Break effect
var _break_timer: float = 0.0
var _is_breaking: bool = false
var _crack_points: Array = []  # Store crack positions for break effect
var _shimmer_offset: float = 0.0

# Forming effect (1.5 second delay when activating)
var _is_forming: bool = false
var _form_timer: float = 0.0
const FORM_DURATION: float = 1.5
var _should_reform: bool = false  # Whether to reform after breaking

func initialize(player: Node2D, max_shield_hits: int) -> void:
	owner_player = player
	max_hits = max_shield_hits
	current_hits = max_hits

func _ready() -> void:
	z_index = 40

func _process(delta: float) -> void:
	if _is_breaking:
		_break_timer += delta
		if _break_timer >= 0.4:
			_is_breaking = false
			_break_timer = 0.0
			_crack_points.clear()
			# After break, start reforming if we should still be in shield mode
			if _should_reform:
				_is_forming = true
				_form_timer = 0.0
				visible = true
			else:
				visible = false
		queue_redraw()
		return
	
	# Handle forming state
	if _is_forming:
		_form_timer += delta
		_pulse_time += delta  # For spinning particles
		if _form_timer >= FORM_DURATION:
			_is_forming = false
			_is_active = true
			current_hits = max_hits  # Fully charged when formed
		queue_redraw()
		return
	
	if not _is_active:
		visible = false  # Hide completely when not active
		return
	
	_pulse_time += delta
	_shimmer_offset += delta * 2.0  # Shimmer animation
	
	# Decay hit flash
	if _hit_flash > 0:
		_hit_flash -= delta * 3.0
	
	queue_redraw()

func update_shield(delta: float) -> void:
	if not _is_active:
		return
	
	# Recharge shield if not at max
	if current_hits < max_hits:
		_is_recharging = true
		_recharge_timer += delta
		
		if _recharge_timer >= recharge_time:
			current_hits += 1
			_recharge_timer = 0.0
			
			if current_hits >= max_hits:
				_is_recharging = false
	else:
		_is_recharging = false
		_recharge_timer = 0.0

func set_active(active: bool) -> void:
	_should_reform = active  # Track whether we should reform after breaking
	
	if active and not _is_active and not _is_forming:
		# Start forming (1.5 second delay)
		_is_forming = true
		_form_timer = 0.0
		visible = true
	elif not active:
		_is_active = false
		_is_forming = false
		visible = _is_breaking  # Only visible during break animation

func set_max_hits(new_max: int) -> void:
	var was_full := current_hits >= max_hits
	max_hits = new_max
	if was_full:
		current_hits = max_hits

func absorb_hit() -> bool:
	"""Try to absorb a hit. Returns true if shield absorbed it."""
	if not _is_active or current_hits <= 0:
		return false
	
	current_hits -= 1
	_hit_flash = 1.0
	
	# Generate crack points for visual effect
	_generate_cracks()
	
	# If shield depleted, trigger break effect and deactivate
	if current_hits <= 0:
		_is_breaking = true
		_break_timer = 0.0
		_is_active = false  # Shield is no longer active after breaking
		visible = true
		# Will need to reform after break animation
	
	# Start recharging
	if current_hits < max_hits:
		_is_recharging = true
		_recharge_timer = 0.0
	
	return true

func _generate_cracks() -> void:
	_crack_points.clear()
	# Generate 3-5 random crack lines
	var num_cracks := randi_range(3, 5)
	for _i in range(num_cracks):
		var start_angle := randf() * TAU
		var start_pos := Vector2(cos(start_angle), sin(start_angle)) * shield_radius
		var crack := {
			"start": start_pos,
			"segments": []
		}
		# Generate jagged line toward center
		var current := start_pos
		var toward_center := -start_pos.normalized()
		for _j in range(randi_range(2, 4)):
			var jitter := Vector2(randf_range(-20, 20), randf_range(-20, 20))
			var next := current + toward_center * randf_range(15, 30) + jitter
			crack["segments"].append({"from": current, "to": next})
			current = next
		_crack_points.append(crack)

func has_charges() -> bool:
	return _is_active and current_hits > 0

func _draw() -> void:
	# Draw break effect (cracking and fading)
	if _is_breaking:
		var break_alpha := 1.0 - (_break_timer / 0.4)
		var break_radius := shield_radius * (1.0 + _break_timer * 0.5)  # Expand as it breaks
		
		# Shattered shield outline
		var shatter_color := Color(0.3, 0.7, 1.0, break_alpha * 0.9)
		draw_arc(Vector2.ZERO, break_radius, 0, TAU, 48, shatter_color, 4.0)
		
		# Draw cracks
		for crack in _crack_points:
			var crack_color := Color(1.0, 1.0, 1.0, break_alpha * 0.9)
			for segment in crack["segments"]:
				draw_line(segment["from"], segment["to"], crack_color, 2.0)
		
		# Particles flying outward
		for i in range(8):
			var angle := (TAU / 8.0) * i + _break_timer * 3.0
			var particle_pos := Vector2(cos(angle), sin(angle)) * (break_radius + _break_timer * 100)
			var particle_color := Color(0.5, 0.9, 1.0, break_alpha * 0.8)
			draw_circle(particle_pos, 4.0 * break_alpha, particle_color)
		return
	
	if not _is_active:
		# Don't draw anything when inactive (no faint circle)
		if _is_forming:
			# Draw forming effect - growing circle
			var form_progress := _form_timer / FORM_DURATION
			var form_radius := shield_radius * form_progress
			var form_alpha := 0.3 * form_progress
			
			# Outer glow building up
			var glow_color := Color(0.3, 0.6, 1.0, form_alpha * 0.5)
			draw_arc(Vector2.ZERO, form_radius + 8, 0, TAU, 48, glow_color, 6.0 * form_progress)
			
			# Main forming circle
			var form_color := Color(0.4, 0.8, 1.0, form_alpha)
			draw_arc(Vector2.ZERO, form_radius, 0, TAU, 48, form_color, 3.0)
			
			# Spinning particles during formation
			for i in range(6):
				var angle := (TAU / 6.0) * i + _pulse_time * 4.0
				var particle_pos := Vector2(cos(angle), sin(angle)) * form_radius
				var particle_color := Color(0.6, 0.9, 1.0, form_alpha * 0.8)
				draw_circle(particle_pos, 3.0, particle_color)
		return
	
	# Shield is active - make it very visible and glowy
	
	# Pulsing effect
	var pulse := sin(_pulse_time * 3.0) * 0.08 + 1.0
	var draw_radius := shield_radius * pulse
	
	# Base alpha - much more opaque when active
	var charge_ratio := float(current_hits) / float(max_hits)
	var base_alpha := 0.7 + charge_ratio * 0.3  # 0.7 to 1.0
	
	# Hit flash makes it even brighter
	var flash_boost := _hit_flash * 0.3
	
	# Multiple outer glow layers for intense glow effect
	var glow_color_outer := Color(0.2, 0.5, 1.0, 0.15 + flash_boost * 0.1)
	draw_arc(Vector2.ZERO, draw_radius + 25, 0, TAU, 48, glow_color_outer, 20.0)
	
	var glow_color_mid := Color(0.3, 0.6, 1.0, 0.25 + flash_boost * 0.15)
	draw_arc(Vector2.ZERO, draw_radius + 12, 0, TAU, 48, glow_color_mid, 12.0)
	
	var glow_color_inner := Color(0.4, 0.7, 1.0, 0.4 + flash_boost * 0.2)
	draw_arc(Vector2.ZERO, draw_radius + 5, 0, TAU, 48, glow_color_inner, 6.0)
	
	# Main shield bubble - thick and bright
	var shield_color := Color(0.4, 0.8, 1.0, base_alpha + flash_boost)
	draw_arc(Vector2.ZERO, draw_radius, 0, TAU, 48, shield_color, 5.0)
	
	# Inner fill - more visible
	var fill_color := Color(0.3, 0.7, 1.0, 0.25 + charge_ratio * 0.15 + flash_boost * 0.2)
	draw_circle(Vector2.ZERO, draw_radius, fill_color)
	
	# Bright inner edge
	var inner_edge := Color(0.6, 0.9, 1.0, 0.5 + flash_boost * 0.3)
	draw_arc(Vector2.ZERO, draw_radius - 3, 0, TAU, 48, inner_edge, 2.0)
	
	# Shimmer effect - brighter moving highlight arcs
	var shimmer_alpha := 0.4 + sin(_shimmer_offset * 2.0) * 0.2
	var shimmer_start := fmod(_shimmer_offset, TAU)
	var shimmer_color := Color(0.9, 1.0, 1.0, shimmer_alpha)
	draw_arc(Vector2.ZERO, draw_radius - 2, shimmer_start, shimmer_start + PI * 0.4, 16, shimmer_color, 6.0)
	draw_arc(Vector2.ZERO, draw_radius - 2, shimmer_start + PI, shimmer_start + PI * 1.4, 16, shimmer_color, 6.0)
	
	# Draw active cracks if we've been hit recently
	if _hit_flash > 0 and _crack_points.size() > 0:
		for crack in _crack_points:
			var crack_alpha := _hit_flash * 0.9
			var crack_color := Color(1.0, 1.0, 1.0, crack_alpha)
			for segment in crack["segments"]:
				draw_line(segment["from"], segment["to"], crack_color, 1.5)
	
	# Recharge indicator
	if _is_recharging:
		var progress := _recharge_timer / recharge_time
		var arc_end := progress * TAU
		var recharge_color := Color(0.5, 0.9, 1.0, 0.6)
		draw_arc(Vector2.ZERO, draw_radius - 5, -PI/2, -PI/2 + arc_end, 32, recharge_color, 2.0)
	
	# Draw hit count indicators (small circles around shield)
	for i in range(max_hits):
		var angle := (TAU / max_hits) * i - PI/2
		var indicator_pos := Vector2(cos(angle), sin(angle)) * (draw_radius + 18)
		var indicator_color: Color
		if i < current_hits:
			indicator_color = Color(0.4, 0.9, 1.0, 0.8)  # Active
		else:
			indicator_color = Color(0.2, 0.4, 0.6, 0.4)  # Depleted
		draw_circle(indicator_pos, 4.0, indicator_color)
